// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { DesktopEntry } from "../entry";
import type { LocalVault, ReadingOperation, VaultMemory, VaultReading } from "../platform/local-vault";

const session = { root: "/synthetic/vault", vault_id: "session-a", vault_identity: "manifest-a" };
const memory: VaultMemory = { id: "m1", revision: 1, note: "Synthetic annotation", source_name: "synthetic.png", source_sha256: "a".repeat(64), captured_at: "2026-10-08T12:00:00Z", updated_at: "2026-10-08T12:00:00Z", state: "active", conflict: null, note_path: "synthetic.md" };
const reading: VaultReading = { machine: { request: { binding: { schema_version: "1.0", operation_id: "synthetic-op", vault_id: "manifest-a", memory_id: "m1", source_id: "m1", source_sha256: memory.source_sha256, expected_revision: 1, captured_at: memory.captured_at }, media_type: "image/png" }, result: { provider: "anthropic", model_id: "synthetic-claude", review_state: "unreviewed", input_manifest_sha256: "b".repeat(64), derivative: { sha256: "c".repeat(64), transform_version: "jpeg-rgb-exif-orient-v1", media_type: "image/jpeg" }, extraction: { schema_version: "1.1", capture_id: "synthetic-op", input_manifest_sha256: "b".repeat(64), summary: null, summary_evidence: [], pages: [{ page_id: "m1", ordinal: 1, transcription: "SYNTHETIC seedlings 12?", legibility: "mixed" }], mentions: [], statements: [], action_suggestions: [], uncertainties: [{ kind: "illegible", description: "The number may be 12; the question mark is unresolved.", evidence: [] }] }, validation_notes: [] } }, human_correction: null };
const readMemory = { ...memory, revision: 2, reading };
const operation = (patch: Partial<ReadingOperation> = {}): ReadingOperation => ({ operation_id: "synthetic-op", memory_id: memory.id, expected_revision: 1, state: "unknown", may_have_been_sent: true, error_code: null, ...patch });
function vault(over: Partial<LocalVault> = {}): LocalVault {
  return { available: true, status: async () => session, select: async () => null, capture: async () => memory, list: async () => [memory], rebuild: async () => [memory], correct: async () => memory, remove: async () => ({ ...memory, state: "deleted", revision: 2 }), restoreNote: async () => memory, source: async () => ({ bytes: [137,80,78,71], mime_type: "image/png", sha256: memory.source_sha256 }), history: async () => [], readingCapability: async () => ({ enabled: true, explanation: "Synthetic connection" }), readingOperations: async () => [], readPhoto: vi.fn(async (_s, _id, _r, op) => ({ operation: operation({ operation_id: op, state: "committed" }), memory: readMemory })), recoverReading: vi.fn(async (_s, op) => ({ operation: operation({ operation_id: op, state: "committed" }), memory: readMemory })), cancelReading: vi.fn(async (_s, op) => operation({ operation_id: op, state: "cancelled" })), correctReading: vi.fn(async (_s, _id, _r, _op, text) => ({ ...readMemory, revision: 3, reading: { ...reading, human_correction: text } })), ...over };
}
const mount = (v: LocalVault) => render(<DesktopEntry vault={v} search="" />);
async function open() { await userEvent.click(await screen.findByRole("button", { name: /Synthetic annotation/ })); }
async function consent() { await userEvent.click(await screen.findByRole("button", { name: "Read this photo with Claude" })); }
async function send() { await consent(); await userEvent.click(screen.getByRole("button", { name: "Send this photo to Claude" })); }
beforeEach(() => { localStorage.clear(); URL.createObjectURL = vi.fn(() => "blob:synthetic"); URL.revokeObjectURL = vi.fn(); });
afterEach(cleanup);

it("requires selected-photo consent and keeps disconnected local capture usable", async () => {
  const v = vault({ readingCapability: async () => ({ enabled: false, explanation: "No private service connection" }) }); mount(v); await open();
  await screen.findByText(/Claude reading is not connected/); expect((screen.getByRole("button", { name: "Read this photo with Claude" }) as HTMLButtonElement).disabled).toBe(true); expect(v.readPhoto).not.toHaveBeenCalled();
  await userEvent.click(screen.getByRole("button", { name: "Back to memories" })); await userEvent.click(screen.getByRole("button", { name: "Capture" })); await userEvent.click(screen.getByRole("button", { name: "Choose photo & save" })); expect(await screen.findByRole("button", { name: /Synthetic annotation/ })).toBeTruthy(); expect(screen.queryByText(/email|sign in/i)).toBeNull();
});
it("never uploads on focus or consent cancellation and shows an attributed uncertain reading beside original", async () => {
  const v = vault(); mount(v); await open(); await consent(); expect(v.readPhoto).not.toHaveBeenCalled(); await userEvent.click(screen.getByRole("button", { name: "Keep it local" })); expect(v.readPhoto).not.toHaveBeenCalled();
  await send(); expect(await screen.findByRole("heading", { name: "Unreviewed machine reading" })).toBeTruthy(); expect(screen.getByText("SYNTHETIC seedlings 12?")).toBeTruthy(); expect(screen.getByText(/question mark is unresolved/)).toBeTruthy(); expect(screen.getByText(/synthetic-claude/)).toBeTruthy();
  fireEvent.load(await screen.findByRole("img", { name: "Original photo for comparison" })); expect(screen.getByText(/Original bytes unchanged/)).toBeTruthy(); expect(v.readPhoto).toHaveBeenCalledWith("session-a", "m1", 1, expect.any(String)); expect(screen.getByText("Synthetic annotation")).toBeTruthy();
});
it("searches effective human reading instead of the superseded machine proposal", async () => {
  const corrected = { ...readMemory, reading: { ...reading, human_correction: "SYNTHETIC marigolds" } }; mount(vault({ list: async (_s, q) => q === "seedlings" ? [] : [corrected] }));
  await userEvent.type(await screen.findByLabelText("Search notes and filenames"), "marigolds"); await userEvent.click(screen.getByRole("button", { name: "Search" })); expect(await screen.findByRole("button", { name: /Synthetic annotation/ })).toBeTruthy();
  await open(); expect(await screen.findByRole("heading", { name: "Your corrected reading" })).toBeTruthy(); expect(screen.getByText("SYNTHETIC marigolds")).toBeTruthy();
});
it("keeps a human reading correction separate and later reprocessing does not overwrite it", async () => {
  let current = readMemory; const v = vault({ list: async () => [current], correctReading: vi.fn(async (_s, _id, _r, _op, text) => current = { ...current, revision: 3, reading: { ...reading, human_correction: text } }), readPhoto: vi.fn(async (_s, _id, _r, op) => ({ operation: operation({ operation_id: op, state: "committed" }), memory: { ...current, revision: 4 } })) }); mount(v); await open();
  await userEvent.click(await screen.findByRole("button", { name: "Correct reading" })); await userEvent.clear(screen.getByLabelText("Your reading correction")); await userEvent.type(screen.getByLabelText("Your reading correction"), "SYNTHETIC marigolds"); await userEvent.click(screen.getByRole("button", { name: "Save reading correction" }));
  expect(await screen.findByRole("heading", { name: "Your corrected reading" })).toBeTruthy(); expect(screen.getByText("Synthetic annotation")).toBeTruthy(); expect(v.correctReading).toHaveBeenCalledWith("session-a", "m1", 2, expect.any(String), "SYNTHETIC marigolds");
  await send(); expect(await screen.findByText("Reading saved in your vault." )).toBeTruthy(); expect(screen.getByText("SYNTHETIC marigolds")).toBeTruthy(); expect(screen.getByText("SYNTHETIC seedlings 12?")).toBeTruthy();
});
it("preserves empty human correction and renders model markup literally", async () => {
  const crafted = { ...reading, machine: { ...reading.machine, result: { ...reading.machine.result, extraction: { ...reading.machine.result.extraction, pages: [{ ...reading.machine.result.extraction.pages[0]!, transcription: "<img src=x onerror=alert(1)> # Human verified" }] } } }, human_correction: "" }; mount(vault({ list: async () => [{ ...readMemory, reading: crafted }] })); await open(); await screen.findByRole("heading", { name: "Your corrected reading" }); expect(screen.getByText("Your reading is intentionally empty.")).toBeTruthy(); expect(screen.getByText("<img src=x onerror=alert(1)> # Human verified")).toBeTruthy(); expect(document.querySelector("img[src=x]")).toBeNull();
});
it("uses disclosed same-operation recovery for an uncertain reading without new dispatch", async () => {
  const op = operation(); const v = vault({ readingOperations: async () => [op] }); mount(v); await open(); await screen.findByText(/may already have been sent/); expect(screen.getByText(/may resend this photo/)).toBeTruthy(); await userEvent.click(screen.getByRole("button", { name: "Retry or recover reading" })); await screen.findByRole("heading", { name: "Unreviewed machine reading" }); expect(v.recoverReading).toHaveBeenCalledWith("session-a", op.operation_id); expect(v.readPhoto).not.toHaveBeenCalled();
});
it("cancels while awaiting transport and ignores its later successful reply", async () => {
  let finish!: (value: { operation: ReadingOperation; memory: VaultMemory }) => void; const v = vault({ readPhoto: vi.fn(() => new Promise<{ operation: ReadingOperation; memory: VaultMemory }>(resolve => { finish = resolve; })) }); mount(v); await open(); await send(); await screen.findByText("Reading this photo with Claude…"); expect(screen.queryByText("Saved in vault · This device only")).toBeNull(); await userEvent.click(screen.getByRole("button", { name: "Cancel reading" })); await screen.findByText(/Reading cancelled locally/); await act(async () => finish({ operation: operation({ state: "committed" }), memory: readMemory })); expect(screen.queryByRole("heading", { name: "Unreviewed machine reading" })).toBeNull(); expect(screen.getByText(/processing or a charge/)).toBeTruthy(); expect(v.cancelReading).toHaveBeenCalledWith("session-a", expect.any(String));
});
it.each(["back", "switch"])("rejects a delayed reading after %s and cancels the original operation", async mode => {
  let finish!: (value: { operation: ReadingOperation; memory: VaultMemory }) => void; const v = vault({ readPhoto: vi.fn(() => new Promise<{ operation: ReadingOperation; memory: VaultMemory }>(resolve => { finish = resolve; })), select: async () => ({ root: "/synthetic/b", vault_id: "session-b", vault_identity: "manifest-b" }), list: async s => s === "session-a" ? [memory] : [] }); mount(v); await open(); await send(); await userEvent.click(screen.getByRole("button", { name: mode === "back" ? "Back to memories" : "Switch vault" })); await act(async () => finish({ operation: operation({ state: "committed" }), memory: readMemory })); expect(screen.queryByText("SYNTHETIC seedlings 12?")).toBeNull(); await waitFor(() => expect(v.cancelReading).toHaveBeenCalledWith("session-a", expect.any(String)));
});
it("retains a stale reading correction draft and requires reviewed current revision", async () => {
  const corrected = vi.fn().mockRejectedValueOnce(new Error("Revision conflict")).mockResolvedValue({ ...readMemory, revision: 4, reading: { ...reading, human_correction: "My retained draft" } }); const list = vi.fn().mockResolvedValueOnce([readMemory]).mockResolvedValue([{ ...readMemory, revision: 3, reading: { ...reading, human_correction: "Current reading" } }]); mount(vault({ correctReading: corrected, list })); await open(); await userEvent.click(await screen.findByRole("button", { name: "Correct reading" })); await userEvent.clear(screen.getByLabelText("Your reading correction")); await userEvent.type(screen.getByLabelText("Your reading correction"), "My retained draft"); await userEvent.click(screen.getByRole("button", { name: "Save reading correction" })); await screen.findByText("Revision conflict"); await userEvent.click(screen.getByRole("button", { name: "Reload latest reading" })); await screen.findByText("Current reading"); expect((screen.getByLabelText("Your reading correction") as HTMLTextAreaElement).value).toBe("My retained draft"); expect((screen.getByRole("button", { name: "Save reading correction" }) as HTMLButtonElement).disabled).toBe(true); await userEvent.click(screen.getByLabelText("I reviewed the latest reading")); await userEvent.click(screen.getByRole("button", { name: "Save reading correction" })); await screen.findByRole("heading", { name: "Your corrected reading" }); expect(corrected.mock.calls[1]![2]).toBe(3); expect(corrected.mock.calls[1]![3]).not.toBe(corrected.mock.calls[0]![3]);
});
it("shows reading and correction provenance in retained history", async () => {
  mount(vault({ list: async () => [readMemory], history: async () => [{ revision: 2, note: memory.note, reading, origin: "machine:anthropic", kind: "machine_reading", recorded_at: memory.captured_at }, { revision: 3, note: memory.note, reading: { ...reading, human_correction: "SYNTHETIC marigolds" }, origin: "human:recall", kind: "reading_correction", recorded_at: memory.captured_at }] })); await open(); await userEvent.click(screen.getByRole("button", { name: "History" })); expect(await screen.findByText(/machine_reading · machine:anthropic/)).toBeTruthy(); expect(screen.getByRole("heading", { name: "Your corrected reading" })).toBeTruthy(); expect(screen.getAllByText(/Unreviewed machine reading/).length).toBeGreaterThan(0);
});
it.each(["missing", "deleted", "conflict"] as const)("publishes authoritative %s on correction reload while retaining the draft", async state => {
  // Native revision-zero diagnostics have no reading or source/note metadata.
  const latest: VaultMemory = state === "conflict" ? { id: memory.id, revision: 0, reading: undefined, state, note: "", note_path: null, source_name: "", source_sha256: "", captured_at: "", updated_at: "", conflict: "SYNTHETIC history conflict" } : { ...readMemory, state, revision: 3 };
  const list = vi.fn().mockResolvedValueOnce([readMemory]).mockResolvedValue([latest]); mount(vault({ list, correctReading: async () => { throw new Error("Reading correction interrupted"); } })); await open(); await userEvent.click(await screen.findByRole("button", { name: "Correct reading" })); await userEvent.clear(screen.getByLabelText("Your reading correction")); await userEvent.type(screen.getByLabelText("Your reading correction"), "Retained draft"); await userEvent.click(screen.getByRole("button", { name: "Save reading correction" })); await screen.findByText("Reading correction interrupted"); await userEvent.click(screen.getByRole("button", { name: "Reload latest reading" })); await waitFor(() => expect((screen.getByRole("button", { name: "Save reading correction" }) as HTMLButtonElement).disabled).toBe(true)); expect((screen.getByLabelText("Your reading correction") as HTMLTextAreaElement).value).toBe("Retained draft"); expect(screen.queryByLabelText("I reviewed the latest reading")).toBeNull(); expect((screen.getByRole("button", { name: "View original" }) as HTMLButtonElement).disabled).toBe(true);
});
it("keeps an unsaved reading draft when returning to comparison and correction", async () => {
  mount(vault({ list: async () => [readMemory] })); await open(); await userEvent.click(await screen.findByRole("button", { name: "Correct reading" })); await userEvent.clear(screen.getByLabelText("Your reading correction")); await userEvent.type(screen.getByLabelText("Your reading correction"), "Keep my unsaved reading"); await userEvent.click(screen.getByRole("button", { name: "Back to reading" })); await userEvent.click(screen.getByRole("button", { name: "Correct reading" })); expect((screen.getByLabelText("Your reading correction") as HTMLTextAreaElement).value).toBe("Keep my unsaved reading");
});
it("preserves reading correction and review requirement through a cancelled vault picker", async () => {
  mount(vault({ list: async () => [readMemory] })); await open(); await userEvent.click(await screen.findByRole("button", { name: "Correct reading" })); await userEvent.clear(screen.getByLabelText("Your reading correction")); await userEvent.type(screen.getByLabelText("Your reading correction"), "Draft during selection"); await userEvent.click(screen.getByRole("button", { name: "Switch vault" })); expect((await screen.findByLabelText("Your reading correction") as HTMLTextAreaElement).value).toBe("Draft during selection");
});
it("permits explicit durable receipt recovery with a disconnected service and a pending-publication diagnostic", async () => {
  const v = vault({ list: async () => [{ ...memory, state: "conflict", conflict: "Pending machine publication", revision: 0 }], readingCapability: async () => ({ enabled: false, explanation: "Not connected" }), readingOperations: async () => [operation({ state: "ready" })] }); mount(v); await userEvent.click(await screen.findByRole("button", { name: /Memory needs attention/ })); await screen.findByText("Reading status: ready"); await userEvent.click(screen.getByRole("button", { name: "Retry or recover reading" })); await screen.findByRole("heading", { name: "Unreviewed machine reading" }); expect(v.recoverReading).toHaveBeenCalledWith("session-a", "synthetic-op"); expect(v.readPhoto).not.toHaveBeenCalled();
});
it("rejects a comparison source error from an older revision after saving a reading correction", async () => {
  let fail!: (e: Error) => void; const source = vi.fn().mockImplementationOnce(() => new Promise((_resolve, reject) => { fail = reject; })).mockResolvedValue({ bytes: [137,80,78,71], mime_type: "image/png", sha256: memory.source_sha256 }); mount(vault({ list: async () => [readMemory], source })); await open(); await userEvent.click(await screen.findByRole("button", { name: "Correct reading" })); await userEvent.clear(screen.getByLabelText("Your reading correction")); await userEvent.type(screen.getByLabelText("Your reading correction"), "Newest human reading"); await userEvent.click(screen.getByRole("button", { name: "Save reading correction" })); await screen.findByRole("heading", { name: "Your corrected reading" }); await act(async () => fail(new Error("Private stale source failure"))); expect(screen.getByRole("heading", { name: "Your corrected reading" })).toBeTruthy(); expect(screen.getByText("Newest human reading")).toBeTruthy(); expect(screen.queryByText(/Private stale source failure/)).toBeNull();
});
it("keeps a read-only draft and reload available until a diagnostic with no reading is repaired", async () => {
  const diagnostic: VaultMemory = { id: memory.id, revision: 0, state: "conflict", note: "", note_path: null, source_name: "", source_sha256: "", captured_at: "", updated_at: "", conflict: "SYNTHETIC authority unavailable" };
  const list = vi.fn().mockResolvedValueOnce([readMemory]).mockResolvedValueOnce([diagnostic]).mockResolvedValue([{ ...readMemory, revision: 3 }]); const correctReading = vi.fn().mockRejectedValueOnce(new Error("Reading correction interrupted")).mockResolvedValue({ ...readMemory, revision: 4, reading: { ...reading, human_correction: "Precious retained draft" } }); mount(vault({ list, correctReading })); await open(); await screen.findByRole("img", { name: "Original photo for comparison" }); await userEvent.click(await screen.findByRole("button", { name: "Correct reading" })); await userEvent.clear(screen.getByLabelText("Your reading correction")); await userEvent.type(screen.getByLabelText("Your reading correction"), "Precious retained draft"); await userEvent.click(screen.getByRole("button", { name: "Save reading correction" })); await screen.findByText("Reading correction interrupted"); await userEvent.click(screen.getByRole("button", { name: "Reload latest reading" })); await screen.findByRole("heading", { name: "Memory needs attention" }); const draft = screen.getByLabelText("Your reading correction") as HTMLTextAreaElement; expect(draft.value).toBe("Precious retained draft"); expect(draft.readOnly).toBe(true); expect((screen.getByRole("button", { name: "Save reading correction" }) as HTMLButtonElement).disabled).toBe(true); expect(screen.queryByRole("img", { name: "Original photo for comparison" })).toBeNull(); await userEvent.click(screen.getByRole("button", { name: "Reload latest reading" })); await screen.findByLabelText("I reviewed the latest reading"); expect(draft.value).toBe("Precious retained draft"); await userEvent.click(screen.getByLabelText("I reviewed the latest reading")); await userEvent.click(screen.getByRole("button", { name: "Save reading correction" })); await screen.findByRole("heading", { name: "Your corrected reading" }); expect(correctReading.mock.calls[1]![2]).toBe(3); expect(correctReading.mock.calls[1]![3]).not.toBe(correctReading.mock.calls[0]![3]);
});
it.each(["reread", "recover", "cancel"] as const)("does not strand a pending original source completion when starting %s", async action => {
  let finish!: (value: { bytes: number[]; mime_type: string; sha256: string }) => void;
  const v = vault({ list: async () => [readMemory], source: () => new Promise(resolve => { finish = resolve; }), readingOperations: async () => action === "reread" ? [] : [operation()], readPhoto: async (_s, _id, _r, op) => ({ operation: operation({ operation_id: op, state: "unknown" }), memory: null }), recoverReading: async () => ({ operation: operation(), memory: null }) }); mount(v); await open(); await screen.findByText("Loading the original photo…"); if (action === "reread") await send(); else await userEvent.click(await screen.findByRole("button", { name: action === "recover" ? "Retry or recover reading" : "Cancel reading" })); await act(async () => finish({ bytes: [137,80,78,71], mime_type: "image/png", sha256: memory.source_sha256 })); expect(screen.getByRole("img", { name: "Original photo for comparison" })).toBeTruthy(); expect(screen.queryByText("Loading the original photo…")).toBeNull();
});
it.each(["reread", "recover", "cancel"] as const)("does not suppress an original source error when starting %s", async action => {
  let fail!: (e: Error) => void;
  const v = vault({ list: async () => [readMemory], source: () => new Promise((_resolve, reject) => { fail = reject; }), readingOperations: async () => action === "reread" ? [] : [operation()], readPhoto: async (_s, _id, _r, op) => ({ operation: operation({ operation_id: op, state: "unknown" }), memory: null }), recoverReading: async () => ({ operation: operation(), memory: null }) }); mount(v); await open(); await screen.findByText("Loading the original photo…"); if (action === "reread") await send(); else await userEvent.click(await screen.findByRole("button", { name: action === "recover" ? "Retry or recover reading" : "Cancel reading" })); await act(async () => fail(new Error("SYNTHETIC current source failure"))); expect(screen.getAllByText(/Original unavailable: SYNTHETIC current source failure/).length).toBeGreaterThan(0); expect(screen.queryByText("Loading the original photo…")).toBeNull(); expect((screen.getByRole("button", { name: "View original" }) as HTMLButtonElement).disabled).toBe(true);
});
